# Common configuration for all models
DATA:
  CACHE_DIR: "experiments/cache"
  CALIB_FRACTION: 0.5
  LIMIT_DATASET_SIZE: false
  MAX_TRAIN_IMAGES: -1
  MAX_VAL_IMAGES: -1
  BATCH_SIZE: 128

TRAINING:
  NUM_EPOCHS: 100
  BATCH_SIZE: 128
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.0001
  GRAD_CLIP_NORM: 1.0
  EARLY_STOPPING_PATIENCE: 20
  CHECKPOINT_FREQUENCY: 10
  DEVICE: "cuda"
  SEED: 42
  LR_SCHEDULER:
    TYPE: "reduce_on_plateau"
    FACTOR: 0.5
    PATIENCE: 10
    MIN_LR: 1e-6

LOSS:
  TARGET_COVERAGE: 0.9
  EFFICIENCY_WEIGHT: 0.05
  CALIBRATION_WEIGHT: 0.1

OUTPUT:
  BASE_DIR: "experiments/results"
  SAVE_FREQUENCY: 10
  PLOT_RESULTS: true
  SAVE_PREDICTIONS: true

VALIDATION:
  EVAL_FREQUENCY: 1  # Evaluate every N epochs
  VERBOSE: true

WANDB:
  USE_WANDB: false
  PROJECT: "conformal-scoring-functions"
  TAGS: ["learnable", "scoring"]